# Generated by Django 5.2.4 on 2025-07-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(default='sample-slug', unique=True),
            preserve_default=False,
        ),
    ]
