# Generated by Django 4.2.23 on 2025-07-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_testcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='Problem',
            new_name='problem',
        ),
    ]
