# Generated by Django 4.2.23 on 2025-07-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('cpp', 'C++'), ('py', 'Python'), ('java', 'Java')], max_length=10),
        ),
    ]
